# Generated by Django 4.1.5 on 2023-02-17 17:37

import apps.authentication.users.signals
import datetime
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='order')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.authentication.users.signals.avatar_directory_path, verbose_name='profile picture')),
                ('full_name', models.CharField(default='', max_length=300, verbose_name='full name')),
                ('location', models.CharField(default='0', max_length=100, verbose_name='location')),
                ('longitude', models.CharField(default='0', max_length=100, verbose_name='longitude')),
                ('latitude', models.CharField(default=0, max_length=100, verbose_name='latitude')),
                ('phone', models.CharField(default=0, max_length=20, verbose_name='phone')),
                ('gender', models.CharField(default='Other', max_length=30, verbose_name='gender')),
                ('birthday', models.DateField(default=datetime.datetime(2005, 2, 21, 17, 37, 51, 524809, tzinfo=datetime.timezone.utc), verbose_name='Birthday')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('privacy', models.BooleanField(default=False, verbose_name='Terms and Conditions')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'AUTHENTICATION - User',
                'verbose_name_plural': 'AUTHENTICATION - Users',
                'db_table': 'apps_authentication_users',
                'ordering': ['order', 'id', 'first_name', 'last_name'],
            },
        ),
    ]
