# Generated by Django 4.1.5 on 2023-02-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='full_name',
        ),
    ]
