# Generated by Django 4.1.5 on 2023-02-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usermodel_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='longitude',
        ),
    ]
